name: Android CI
on:
  push:
    branches:
      - main  # 监听 main 分支的代码推送
  pull_request:
    branches:
      - main  # 监听 main 分支的 PR
jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu 最新的运行环境
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 拉取代码
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build APK
        run: ./gradlew assembleRelease  # 构建 Release APK
      - name: Build AAB
        run: ./gradlew bundleRelease  # 构建 Release AAB
      - name: Upload APK as artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk  # APK 路径
      - name: Upload AAB as artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release.aab
          path: app/build/outputs/bundle/release/app-release.aab  # AAB 路径
